### ISSUE TITLE
UART BMS Communication

### ISSUE THREAD

**Issue by MichaelCastiau** [etransport/PySWIM#1]
Hello. First of all thank u for the current publishing of the Ninebot protocol details. I have been trying to create an UART connection with the internal BMS of the included battery (direct connection from USB2Serial board to BMS), without success. Do you know which hex bytes & baudrate I have to send on the UART connection to read/write registers? I have been trying without any success.

Hexs  I have tried:
- 5aa502012201105aa5020122feef
- 5aa50201220110
- 5aa50001220110

I don't know if I'm supposed to send the 5AA5 bytes with a direct connection to the BMS, really a bit lost here, would you mind helping?

Also some context on why I want to try this: I have bought a Ninebot some 6 months ago and have been disappointed several times by the control board, so much so that I'm working on creating a custom control board, with high quality components. The board of the first scooter burnt out a couple of weeks after purchasing and the second one a couple of months after receiving a new scooter. This board is now cast in silicone, making it impossible to carry out a repair. If I figure out the communication protocol of the included BMS, I could configure a custom control board + interface.

My plan in to replace the interface by a waterproof touchscreen, not only featuring speed & battery status, but also battery health, location services (maybe integrate with Google services?).

**Comment by flowswitch** [comment]
Hello. Please check this thread: https://github.com/etransport/py9b/issues/4
